apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdk = 37
    namespace = 'com.xlythe.calculator.material'
    defaultConfig {
        minSdk = 24
        targetSdk = 37
    }
    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = '11'
    }

    resourcePrefix 'bscalc_'
    lint {
        disable 'MissingTranslation'
    }

}

dependencies {
    api project(':circularreveal')
    api 'androidx.appcompat:appcompat:1.7.1'
    api 'androidx.preference:preference-ktx:1.2.1'
    api 'androidx.recyclerview:recyclerview:1.4.0'
    api 'com.google.android.material:material:1.14.0'
    implementation files(projectDir, 'libs/arity-2.1.7.jar')
}
